[project]
name = "split-multilang-lyric"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "charset-normalizer>=3.4.3",
    "colorama>=0.4.6",
    "mutagen>=1.47.0",
    "pylrc>=0.1.2",
]
